### ISSUE TITLE
cannot read property name of null

### ISSUE THREAD

**Issue by thetayloredman** [eslachance/carrots#6]
Error:
```
17-09-2020 12:01:05 | ::1 | /install
17-09-2020 12:02:06 | ::1 | /install
17-09-2020 12:02:06 | ::1 | /
1 string
TypeError: /Users/logandevine/Documents/GitHub/carrots/pages/index.ejs:3
    1| <%- include('blocks/header', {path, auth, settings}) %>
    2| 			<% articles.forEach(el => {%>
 >> 3| 				<div class="post-info"><a href="/user/<%= el.user.username %>"><%= el.account.name %></a> - <span class="longdate"><%= el.date %></span></div>
    4| 				<article class="post">
    5| 					<header><a href="/view/<%= el.id %>"><%= el.title %></a></header>
    6| 					<main class="post"><%- el.rendered %></main>

Cannot read property 'name' of null
    at eval (/Users/logandevine/Documents/GitHub/carrots/pages/index.ejs:16:37)
    at Array.forEach (<anonymous>)
    at eval (/Users/logandevine/Documents/GitHub/carrots/pages/index.ejs:11:17)
    at index (/Users/logandevine/Documents/GitHub/carrots/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/Users/logandevine/Documents/GitHub/carrots/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/Users/logandevine/Documents/GitHub/carrots/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/Users/logandevine/Documents/GitHub/carrots/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/logandevine/Documents/GitHub/carrots/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/logandevine/Documents/GitHub/carrots/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/logandevine/Documents/GitHub/carrots/node_modules/express/lib/response.js:1012:7)
```
*(Fresh install)*

**Comment by thetayloredman** [comment]
Works after a restart, seems like you are making it redirect too fast

**Comment by thetayloredman** [comment]
Ancient issue, closing myself
